name = "Huffy's Cocaine Bear";
picture = "Huffy_Cocaine_Bear/imagesets/Huffys_CocaineBear_smalllogo.edds";
logoSmall = "Huffy_Cocaine_Bear/imagesets/Huffys_CocaineBear_smalllogo.edds";
logo = "Huffy_Cocaine_Bear/imagesets/Huffys_CocaineBear_smalllogo.edds";
logoOver = "Huffy_Cocaine_Bear/imagesets/Huffys_CocaineBear_smalllogo_hover.edds";
action = "https://steamcommunity.com/profiles/76561198072019228/myworkshopfiles/?appid=221100";
tooltip = "Huffy's Cocaine Bear";
overview = "Huffy's Cocaine Bear";
author = "Huffy";
hidePicture = 0;